// Data sourced from public rankings, search results, community watchlist, and automated discovery.
// Last updated: 2026-06-03.

const TOOLS = [
  {
    id: 1,
    name: "ChatGPT",
    slug: "chatgpt",
    description: "OpenAI's conversational AI — the most visited AI tool globally with 5.6B monthly site visits. Supports writing, coding, image generation (DALL·E), web browsing, and multi-step reasoning. The default AI for most users.",
    url: "https://chatgpt.com",
    affiliate: "",
    category: "chat",
    pricing: "freemium",
    badge: "hot",
    tags: ["conversation", "writing", "coding", "image generation", "web browsing"],
    scenarios: ["marketing", "developers", "students", "business"],
    alternatives: ["claude", "gemini", "grok", "deepseek", "le-chat"]
  },
  {
    id: 2,
    name: "Claude",
    slug: "claude",
    description: "Anthropic's AI assistant with industry-leading long-context reasoning (200K tokens). Growing fast — 18.7% month-over-month traffic growth. Favored by developers for its nuanced coding, analysis, and safe enterprise deployment.",
    url: "https://claude.ai",
    affiliate: "",
    category: "chat",
    pricing: "freemium",
    badge: "trending",
    tags: ["conversation", "analysis", "coding", "long context", "enterprise"],
    scenarios: ["developers", "business", "students", "research"],
    alternatives: ["chatgpt", "gemini", "deepseek", "grok"]
  },
  {
    id: 3,
    name: "Gemini",
    slug: "gemini",
    description: "Google's multimodal AI, deeply integrated with Google Workspace. Gemini app has more downloads than ChatGPT on mobile. 2M token context window — the largest among major chatbots.",
    url: "https://gemini.google.com",
    affiliate: "",
    category: "chat",
    pricing: "freemium",
    badge: "hot",
    tags: ["conversation", "multimodal", "workspace", "2M context", "coding"],
    scenarios: ["business", "students", "developers", "research"],
    alternatives: ["chatgpt", "claude", "grok", "deepseek"]
  },
  {
    id: 4,
    name: "Grok",
    slug: "grok",
    description: "xAI's chatbot with real-time X (Twitter) data access and an unfiltered, witty personality. 160M monthly visits. Integrated into the X platform for premium subscribers.",
    url: "https://grok.com",
    affiliate: "",
    category: "chat",
    pricing: "freemium",
    badge: "",
    tags: ["conversation", "real-time", "twitter", "unfiltered"],
    scenarios: ["social media", "research", "business"],
    alternatives: ["chatgpt", "claude", "gemini", "deepseek"]
  },
  {
    id: 5,
    name: "DeepSeek",
    slug: "deepseek",
    description: "The Chinese AI lab that went viral in early 2025 with open-weight reasoning models rivaling OpenAI. Peaked at 647M monthly visits. Still a top player in open-source AI with exceptional math and coding.",
    url: "https://chat.deepseek.com",
    affiliate: "",
    category: "chat",
    pricing: "free",
    badge: "",
    tags: ["conversation", "reasoning", "open-source", "coding", "math"],
    scenarios: ["developers", "students", "research"],
    alternatives: ["chatgpt", "claude", "gemini", "grok"]
  },
  {
    id: 6,
    name: "Midjourney",
    slug: "midjourney",
    description: "The gold standard for AI image generation, consistently ranked #1 in quality by independent reviewers. Known for cinematic aesthetics and photorealistic output. Used by professional designers and artists worldwide.",
    url: "https://midjourney.com",
    affiliate: "",
    category: "image",
    pricing: "paid",
    badge: "hot",
    tags: ["image generation", "art", "design", "photorealistic", "cinematic"],
    scenarios: ["designers", "marketing", "creators", "art"],
    alternatives: ["dall-e-3", "adobe-firefly", "ideogram", "leonardo-ai", "recraft"]
  },
  {
    id: 7,
    name: "DALL·E 3",
    slug: "dall-e-3",
    description: "OpenAI's text-to-image model, accessible through ChatGPT and the API. Praised for prompt-following accuracy and ease of use. Best for beginners who want quick, reliable image generation.",
    url: "https://openai.com/dall-e-3",
    affiliate: "",
    category: "image",
    pricing: "freemium",
    badge: "",
    tags: ["image generation", "chatgpt integration", "prompt accuracy", "beginner-friendly"],
    scenarios: ["marketing", "creators", "students", "business"],
    alternatives: ["midjourney", "adobe-firefly", "ideogram", "stable-diffusion"]
  },
  {
    id: 8,
    name: "Adobe Firefly",
    slug: "adobe-firefly",
    description: "Adobe's generative AI, embedded in Photoshop, Illustrator, and Premiere. Trained on Adobe Stock and public domain — the safest choice for commercial use. Generative Fill is a standout feature.",
    url: "https://firefly.adobe.com",
    affiliate: "",
    category: "image",
    pricing: "freemium",
    badge: "",
    tags: ["image generation", "photoshop", "commercial safe", "generative fill", "design"],
    scenarios: ["designers", "marketing", "business", "creators"],
    alternatives: ["midjourney", "dall-e-3", "canva-ai", "ideogram"]
  },
  {
    id: 9,
    name: "Ideogram",
    slug: "ideogram",
    description: "AI image generator with a unique strength: accurate text rendering inside images. Ideal for logos, posters, and designs requiring precise typography. Version 3.0 delivers impressive quality.",
    url: "https://ideogram.ai",
    affiliate: "",
    category: "image",
    pricing: "freemium",
    badge: "",
    tags: ["image generation", "typography", "logos", "posters", "text rendering"],
    scenarios: ["designers", "marketing", "business"],
    alternatives: ["midjourney", "dall-e-3", "adobe-firefly", "recraft"]
  },
  {
    id: 10,
    name: "Sora",
    slug: "sora",
    description: "OpenAI's text-to-video model. Sora 2 generates realistic, physics-aware video clips with improved consistency. A major step toward AI filmmaking, available via ChatGPT Plus/Pro subscriptions.",
    url: "https://sora.com",
    affiliate: "",
    category: "video",
    pricing: "paid",
    badge: "hot",
    tags: ["video generation", "text-to-video", "filmmaking", "physics simulation"],
    scenarios: ["creators", "marketing", "filmmaking"],
    alternatives: ["runway", "pika", "kling-ai", "veo-3", "hailuo-ai"]
  },
  {
    id: 11,
    name: "Runway",
    slug: "runway",
    description: "Professional AI video suite. Gen-4 model offers advanced video generation, motion tracking, and real-time editing. The go-to platform for creative professionals and VFX artists.",
    url: "https://runwayml.com",
    affiliate: "",
    category: "video",
    pricing: "paid",
    badge: "",
    tags: ["video generation", "video editing", "VFX", "motion tracking", "professional"],
    scenarios: ["creators", "filmmaking", "marketing"],
    alternatives: ["sora", "pika", "kling-ai", "veo-3"]
  },
  {
    id: 12,
    name: "Pika",
    slug: "pika",
    description: "Viral AI video tool known for creative effects like 'squish it' and 'melt it'. Pika 2.1 adds scene ingredients, lip sync, and sound effects. Fun, fast, and increasingly powerful for social content.",
    url: "https://pika.art",
    affiliate: "",
    category: "video",
    pricing: "freemium",
    badge: "",
    tags: ["video generation", "creative effects", "lip sync", "sound effects"],
    scenarios: ["creators", "social media", "marketing"],
    alternatives: ["runway", "sora", "kling-ai", "hailuo-ai"]
  },
  {
    id: 13,
    name: "Kling AI",
    slug: "kling-ai",
    description: "Kuaishou's AI video generator. Kling 1.6 is a top budget-friendly option praised by independent reviewers. Strong character consistency and motion smoothness. A serious Chinese competitor.",
    url: "https://klingai.com",
    affiliate: "",
    category: "video",
    pricing: "freemium",
    badge: "trending",
    tags: ["video generation", "budget-friendly", "character consistency", "motion"],
    scenarios: ["creators", "social media", "marketing"],
    alternatives: ["runway", "pika", "sora", "hailuo-ai"]
  },
  {
    id: 14,
    name: "GitHub Copilot",
    slug: "github-copilot",
    description: "The most widely adopted AI coding assistant with 1.3M+ paid users. Deeply integrated into VS Code and JetBrains. Copilot X adds chat, code review, and CLI assistance. The safe enterprise choice.",
    url: "https://github.com/features/copilot",
    affiliate: "",
    category: "coding",
    pricing: "paid",
    badge: "",
    tags: ["code completion", "IDE", "chat", "code review", "enterprise"],
    scenarios: ["developers", "business"],
    alternatives: ["cursor", "windsurf", "claude-code"]
  },
  {
    id: 15,
    name: "Cursor",
    slug: "cursor",
    description: "The AI code editor leading the pack in 2025. Valued at $9B. Chat with your entire codebase, apply multi-file edits inline, and enjoy VS Code compatibility with AI superpowers. Developer favorite.",
    url: "https://cursor.com",
    affiliate: "",
    category: "coding",
    pricing: "freemium",
    badge: "hot",
    tags: ["code editor", "AI programming", "codebase chat", "inline edits", "multi-file"],
    scenarios: ["developers"],
    alternatives: ["github-copilot", "windsurf", "claude-code"]
  },
  {
    id: 16,
    name: "Windsurf",
    slug: "windsurf",
    description: "Codeium's AI-powered IDE with Cascade — an agentic coding AI that understands your project and writes multi-file changes. Formerly Codeium, now a top Cursor rival with strong enterprise adoption.",
    url: "https://codeium.com/windsurf",
    affiliate: "",
    category: "coding",
    pricing: "freemium",
    badge: "trending",
    tags: ["AI IDE", "agentic coding", "multi-file edits", "enterprise"],
    scenarios: ["developers", "business"],
    alternatives: ["cursor", "github-copilot", "claude-code"]
  },
  {
    id: 17,
    name: "Claude Code",
    slug: "claude-code",
    description: "Anthropic's terminal-based AI coding agent. Runs directly in your terminal with full project context, file editing, git operations, and shell commands. Developer darling for depth and reliability.",
    url: "https://docs.anthropic.com/en/docs/claude-code",
    affiliate: "",
    category: "coding",
    pricing: "paid",
    badge: "trending",
    tags: ["terminal", "AI agent", "coding", "git", "shell"],
    scenarios: ["developers"],
    alternatives: ["cursor", "github-copilot", "windsurf"]
  },
  {
    id: 18,
    name: "Bolt.new",
    slug: "bolt-new",
    description: "Prompt-to-fullstack-app in the browser. Describe your app idea and Bolt generates a running web application with frontend, backend, and database. Deploy with one click. Fastest path from idea to product.",
    url: "https://bolt.new",
    affiliate: "",
    category: "coding",
    pricing: "freemium",
    badge: "hot",
    tags: ["app builder", "fullstack", "no-code", "deploy", "browser-based"],
    scenarios: ["developers", "business", "creators"],
    alternatives: ["lovable", "replit-agent", "v0"]
  },
  {
    id: 19,
    name: "ElevenLabs",
    slug: "elevenlabs",
    description: "Industry-leading AI voice synthesis and cloning. Generate natural voiceovers in 32 languages, clone voices from short samples, produce audiobooks. Also offers AI music generation.",
    url: "https://elevenlabs.io",
    affiliate: "",
    category: "audio",
    pricing: "freemium",
    badge: "hot",
    tags: ["text-to-speech", "voice cloning", "audiobooks", "multilingual", "music"],
    scenarios: ["creators", "marketing", "business", "education"],
    alternatives: ["murf-ai", "descript", "suno"]
  },
  {
    id: 20,
    name: "Suno",
    slug: "suno",
    description: "Create full, radio-quality songs from text prompts. Suno V4 delivers improved vocals, richer instrumentation, and longer compositions. Describe a genre and theme, get a complete song in seconds.",
    url: "https://suno.ai",
    affiliate: "",
    category: "audio",
    pricing: "freemium",
    badge: "hot",
    tags: ["music generation", "songs", "lyrics", "creative"],
    scenarios: ["creators", "social media", "music"],
    alternatives: ["udio", "elevenlabs"]
  },
  {
    id: 21,
    name: "Udio",
    slug: "udio",
    description: "AI music generator built by former Google DeepMind researchers. Known for high-quality instrumentals and vocal realism. A strong Suno alternative with a different creative flavor.",
    url: "https://udio.com",
    affiliate: "",
    category: "audio",
    pricing: "freemium",
    badge: "",
    tags: ["music generation", "instrumentals", "vocals", "creative"],
    scenarios: ["creators", "music"],
    alternatives: ["suno", "elevenlabs"]
  },
  {
    id: 22,
    name: "Perplexity",
    slug: "perplexity",
    description: "AI-powered search engine that combines LLM intelligence with live web access. Provides cited, verifiable answers with source links. The go-to research companion for fact-checked AI responses.",
    url: "https://perplexity.ai",
    affiliate: "",
    category: "research",
    pricing: "freemium",
    badge: "hot",
    tags: ["search", "research", "citations", "web access", "fact-checking"],
    scenarios: ["students", "research", "business", "developers"],
    alternatives: ["chatgpt", "notebooklm", "gemini"]
  },
  {
    id: 23,
    name: "Grammarly",
    slug: "grammarly",
    description: "The ubiquitous AI writing assistant. Beyond grammar — tone adjustments, generative rewriting, plagiarism detection, and enterprise style guides. Works across every app and browser.",
    url: "https://grammarly.com",
    affiliate: "",
    category: "writing",
    pricing: "freemium",
    badge: "",
    tags: ["grammar", "writing", "tone", "proofreading", "enterprise"],
    scenarios: ["students", "business", "marketing", "developers"],
    alternatives: ["jasper", "chatgpt", "claude"]
  },
  {
    id: 24,
    name: "Jasper",
    slug: "jasper",
    description: "Enterprise AI marketing platform for on-brand content at scale. Generates blog posts, ad copy, emails, and social content with built-in brand voice consistency. Marketing team favorite.",
    url: "https://jasper.ai",
    affiliate: "",
    category: "writing",
    pricing: "paid",
    badge: "",
    tags: ["content marketing", "copywriting", "brand voice", "enterprise"],
    scenarios: ["marketing", "business"],
    alternatives: ["copy-ai", "chatgpt", "grammarly", "claude"]
  },
  {
    id: 25,
    name: "Canva AI",
    slug: "canva-ai",
    description: "Canva's Magic Studio brings AI to 200M+ users. AI design generation, background remover, Magic Write, and brand kit automation. The most accessible AI design tool for non-designers.",
    url: "https://canva.com",
    affiliate: "",
    category: "design",
    pricing: "freemium",
    badge: "",
    tags: ["graphic design", "branding", "templates", "magic studio", "beginner-friendly"],
    scenarios: ["designers", "marketing", "business", "students", "creators"],
    alternatives: ["figma-ai", "adobe-firefly", "gamma"]
  },
  {
    id: 26,
    name: "Figma AI",
    slug: "figma-ai",
    description: "AI features built into the industry-standard UI/UX design tool. Auto-layout suggestions, design-to-code, AI asset generation, and smart layer renaming. Essential for product design teams.",
    url: "https://figma.com",
    affiliate: "",
    category: "design",
    pricing: "freemium",
    badge: "",
    tags: ["UI design", "prototyping", "design-to-code", "collaboration", "teams"],
    scenarios: ["designers", "developers", "business"],
    alternatives: ["canva-ai", "adobe-firefly"]
  },
  {
    id: 27,
    name: "Notion AI",
    slug: "notion-ai",
    description: "AI embedded in Notion's all-in-one workspace. Summarize notes, generate documents, translate, Q&A your knowledge base, and automate workflows. Used by millions of teams and individuals.",
    url: "https://notion.so/product/ai",
    affiliate: "",
    category: "productivity",
    pricing: "paid",
    badge: "",
    tags: ["notes", "knowledge management", "automation", "workspace", "teams"],
    scenarios: ["business", "students", "developers"],
    alternatives: ["gamma", "chatgpt", "claude"]
  },
  {
    id: 28,
    name: "Gamma",
    slug: "gamma",
    description: "Create beautiful presentations, documents, and web pages in seconds using AI. Paste an outline and Gamma generates polished, interactive decks. Export to PPTX or publish as a live site.",
    url: "https://gamma.app",
    affiliate: "",
    category: "productivity",
    pricing: "freemium",
    badge: "trending",
    tags: ["presentations", "documents", "publishing", "design"],
    scenarios: ["business", "students", "marketing", "creators"],
    alternatives: ["canva-ai", "notion-ai"]
  },
  {
    id: 29,
    name: "Copy.ai",
    slug: "copy-ai",
    description: "The first GTM (go-to-market) AI platform. Automates sales prospecting, marketing campaigns, lead enrichment, and workflow orchestration. AI agents work together for end-to-end GTM motions.",
    url: "https://copy.ai",
    affiliate: "",
    category: "marketing",
    pricing: "freemium",
    badge: "",
    tags: ["GTM", "sales", "workflows", "agents", "marketing automation"],
    scenarios: ["marketing", "business"],
    alternatives: ["jasper", "chatgpt", "claude"]
  },
  {
    id: 30,
    name: "Synthesia",
    slug: "synthesia",
    description: "Create professional videos with photorealistic AI avatars — no cameras or studios needed. Supports 140+ languages. Used by 50,000+ companies for training, marketing, and sales videos.",
    url: "https://synthesia.io",
    affiliate: "",
    category: "video",
    pricing: "paid",
    badge: "",
    tags: ["AI avatars", "video creation", "enterprise", "multilingual", "training"],
    scenarios: ["business", "marketing", "education"],
    alternatives: ["heygen", "runway", "descript"]
  }
];

const CATEGORIES = [
  { id: "all", name: "All Tools", icon: "✨" },
  { id: "chat", name: "Chat & Assistants", icon: "💬" },
  { id: "writing", name: "Writing", icon: "✍️" },
  { id: "image", name: "Image Generation", icon: "🎨" },
  { id: "video", name: "Video", icon: "🎬" },
  { id: "coding", name: "Coding", icon: "💻" },
  { id: "audio", name: "Audio & Music", icon: "🎵" },
  { id: "design", name: "Design", icon: "🎯" },
  { id: "marketing", name: "Marketing", icon: "📢" },
  { id: "productivity", name: "Productivity", icon: "⚡" },
  { id: "research", name: "Research", icon: "🔬" }
];

const PRICING_OPTIONS = [
  { id: "all", name: "All" },
  { id: "free", name: "Free" },
  { id: "freemium", name: "Freemium" },
  { id: "paid", name: "Paid" }
];

const SCENARIOS = [
  { id: "developers", name: "For Developers", icon: "💻", description: "AI tools that help you code faster, debug smarter, and ship better software." },
  { id: "marketing", name: "For Marketing", icon: "📢", description: "Content creation, copywriting, social media, and campaign automation tools." },
  { id: "designers", name: "For Designers", icon: "🎨", description: "Image generation, UI design, branding, and creative asset production." },
  { id: "creators", name: "For Creators", icon: "🎬", description: "Video, audio, music, and content creation tools for YouTubers, podcasters, and artists." },
  { id: "business", name: "For Business", icon: "💼", description: "Productivity, automation, presentations, and enterprise AI solutions." },
  { id: "students", name: "For Students", icon: "📚", description: "Research, writing, studying, and learning tools to ace your academic work." }
];

const SORT_OPTIONS = [
  { id: "default", name: "Featured" },
  { id: "name-asc", name: "Name A-Z" },
  { id: "name-desc", name: "Name Z-A" },
  { id: "newest", name: "Newest First" }
];
