// Data sourced from public rankings, search results, community watchlist, and automated discovery.
// Last updated: 2026-06-08.

const TOOLS = [
  {
    id: 1,
    name: "ChatGPT",
    slug: "chatgpt",
    description: "OpenAI's flagship AI — now on GPT-5.4 with o3 reasoning, multimodal capabilities, and autonomous agent features. The most visited AI tool globally. Handles writing, coding, research, image generation, and multi-step workflows.",
    url: "https://chatgpt.com",
    affiliate: "",
    category: "chat",
    pricing: "freemium",
    badge: "hot",
    tags: ["conversation", "writing", "coding", "reasoning", "agents"],
    scenarios: ["marketing", "developers", "students", "business", "research"],
    alternatives: ["claude", "gemini", "grok", "deepseek", "le-chat"]
  },
  {
    id: 2,
    name: "Claude",
    slug: "claude",
    description: "Anthropic's Claude Opus 4.6 leads agentic coding benchmarks (80.8% SWE-bench). Long-context reasoning, computer use, and MCP protocol support. The top choice for developers and enterprises needing reliable, safe AI.",
    url: "https://claude.ai",
    affiliate: "",
    category: "chat",
    pricing: "freemium",
    badge: "hot",
    tags: ["conversation", "coding", "agents", "computer use", "enterprise"],
    scenarios: ["developers", "business", "students", "research"],
    alternatives: ["chatgpt", "gemini", "deepseek", "grok"]
  },
  {
    id: 3,
    name: "Gemini",
    slug: "gemini",
    description: "Google's Gemini 2.5 Pro / 3.1 Pro with 1M+ token context and 120 tokens/sec throughput — fastest among major models. Deep Google Workspace integration and native grounding via Google Search.",
    url: "https://gemini.google.com",
    affiliate: "",
    category: "chat",
    pricing: "freemium",
    badge: "hot",
    tags: ["conversation", "multimodal", "workspace", "fast", "search grounding"],
    scenarios: ["business", "students", "developers", "research"],
    alternatives: ["chatgpt", "claude", "grok", "deepseek"]
  },
  {
    id: 4,
    name: "Grok",
    slug: "grok",
    description: "xAI's Grok 4.3 Beta with real-time X data access and unfiltered personality. Strong reasoning benchmarks. Integrated into the X platform for premium subscribers with image generation capabilities.",
    url: "https://grok.com",
    affiliate: "",
    category: "chat",
    pricing: "freemium",
    badge: "trending",
    tags: ["conversation", "real-time", "twitter", "reasoning", "unfiltered"],
    scenarios: ["social media", "research", "business"],
    alternatives: ["chatgpt", "claude", "gemini", "deepseek"]
  },
  {
    id: 5,
    name: "DeepSeek",
    slug: "deepseek",
    description: "DeepSeek V4 — the cost killer. Roughly 50x cheaper than Claude Opus 4.6 on input tokens (~$0.28/M tokens). Open-weight reasoning models with exceptional math and coding. The go-to for budget-conscious developers.",
    url: "https://chat.deepseek.com",
    affiliate: "",
    category: "chat",
    pricing: "free",
    badge: "trending",
    tags: ["conversation", "reasoning", "open-source", "coding", "budget"],
    scenarios: ["developers", "students", "research"],
    alternatives: ["chatgpt", "claude", "gemini", "qwen"]
  },
  {
    id: 6,
    name: "Llama 4",
    slug: "llama-4",
    description: "Meta's open-source Llama 4 powers the largest fine-tuning ecosystem. Largest community, most forks, and widest hardware support. The default choice for self-hosted and on-device AI deployments in 2026.",
    url: "https://llama.meta.com",
    affiliate: "",
    category: "chat",
    pricing: "free",
    badge: "hot",
    tags: ["open source", "self-hosted", "fine-tuning", "on-device"],
    scenarios: ["developers", "research", "business"],
    alternatives: ["deepseek", "mistral", "qwen", "gemma"]
  },
  {
    id: 7,
    name: "Le Chat",
    slug: "le-chat",
    description: "Mistral's European AI assistant — now with Mistral Medium 3.5 and Small 4 models. Fast, multilingual, with strong privacy guarantees. Web search, image generation via Flux, and code execution. The EU's answer to ChatGPT.",
    url: "https://chat.mistral.ai",
    affiliate: "",
    category: "chat",
    pricing: "freemium",
    badge: "trending",
    tags: ["conversation", "multilingual", "privacy", "european", "coding"],
    scenarios: ["business", "developers", "students"],
    alternatives: ["chatgpt", "claude", "deepseek", "llama-4"]
  },
  {
    id: 8,
    name: "Qwen",
    slug: "qwen",
    description: "Alibaba's Qwen 3.7 Max supports 201 languages — the most multilingual AI. Strong across chat, coding, and multimodal tasks. A top open-source contender with competitive benchmarks against GPT-4 class models.",
    url: "https://tongyi.aliyun.com",
    affiliate: "",
    category: "chat",
    pricing: "freemium",
    badge: "trending",
    tags: ["conversation", "multilingual", "open source", "201 languages", "coding"],
    scenarios: ["developers", "business", "research"],
    alternatives: ["deepseek", "llama-4", "chatgpt", "claude"]
  },
  {
    id: 9,
    name: "Midjourney",
    slug: "midjourney",
    description: "Still the gold standard for AI image generation. V7 delivers cinematic photorealism and precise style control. Used by professional designers, artists, and major brands for campaign-quality visuals.",
    url: "https://midjourney.com",
    affiliate: "",
    category: "image",
    pricing: "paid",
    badge: "hot",
    tags: ["image generation", "art", "design", "photorealistic", "cinematic"],
    scenarios: ["designers", "marketing", "creators", "art"],
    alternatives: ["dall-e-3", "adobe-firefly", "ideogram", "recraft"]
  },
  {
    id: 10,
    name: "DALL·E 3",
    slug: "dall-e-3",
    description: "OpenAI's text-to-image model integrated into ChatGPT. Praised for prompt accuracy and ease of use. Best for beginners who want quick, reliable image generation without leaving the chat interface.",
    url: "https://openai.com/dall-e-3",
    affiliate: "",
    category: "image",
    pricing: "freemium",
    badge: "",
    tags: ["image generation", "chatgpt", "prompt accuracy", "beginner-friendly"],
    scenarios: ["marketing", "creators", "students", "business"],
    alternatives: ["midjourney", "adobe-firefly", "ideogram", "recraft"]
  },
  {
    id: 11,
    name: "Adobe Firefly",
    slug: "adobe-firefly",
    description: "Adobe's generative AI embedded in Photoshop, Illustrator, and Premiere. Trained on Adobe Stock — the safest commercial choice. Generative Fill and vector generation are standout features for professionals.",
    url: "https://firefly.adobe.com",
    affiliate: "",
    category: "image",
    pricing: "freemium",
    badge: "",
    tags: ["image generation", "photoshop", "commercial safe", "generative fill"],
    scenarios: ["designers", "marketing", "business"],
    alternatives: ["midjourney", "dall-e-3", "canva-ai", "ideogram"]
  },
  {
    id: 12,
    name: "Ideogram",
    slug: "ideogram",
    description: "AI image generator specializing in accurate text rendering within images. Perfect for logos, posters, and designs requiring precise typography. Version 3.0 delivers impressive quality at the free tier.",
    url: "https://ideogram.ai",
    affiliate: "",
    category: "image",
    pricing: "freemium",
    badge: "",
    tags: ["image generation", "typography", "logos", "posters", "text rendering"],
    scenarios: ["designers", "marketing"],
    alternatives: ["midjourney", "dall-e-3", "adobe-firefly", "recraft"]
  },
  {
    id: 13,
    name: "Sora",
    slug: "sora",
    description: "OpenAI's text-to-video model — now Sora 2 with improved physics simulation and consistency. Available via ChatGPT Plus/Pro. A paradigm shift for content creators and indie filmmakers.",
    url: "https://sora.com",
    affiliate: "",
    category: "video",
    pricing: "paid",
    badge: "hot",
    tags: ["video generation", "text-to-video", "filmmaking", "physics"],
    scenarios: ["creators", "filmmaking", "marketing"],
    alternatives: ["runway", "pika", "kling-ai", "veo-3"]
  },
  {
    id: 14,
    name: "Runway",
    slug: "runway",
    description: "Professional AI video suite. Gen-4 offers advanced video generation, motion tracking, and real-time editing. The go-to for VFX artists and creative agencies needing a complete video studio.",
    url: "https://runwayml.com",
    affiliate: "",
    category: "video",
    pricing: "paid",
    badge: "",
    tags: ["video generation", "video editing", "VFX", "motion tracking"],
    scenarios: ["creators", "filmmaking", "marketing"],
    alternatives: ["sora", "pika", "kling-ai", "veo-3"]
  },
  {
    id: 15,
    name: "Pika",
    slug: "pika",
    description: "Viral AI video tool — Pika 2.1 adds scene ingredients, lip sync, and sound effects. Fun creative effects like 'squish it' and 'melt it'. Perfect for social media content with fast generation.",
    url: "https://pika.art",
    affiliate: "",
    category: "video",
    pricing: "freemium",
    badge: "",
    tags: ["video generation", "creative effects", "lip sync", "social media"],
    scenarios: ["creators", "social media", "marketing"],
    alternatives: ["runway", "sora", "kling-ai"]
  },
  {
    id: 16,
    name: "Kling AI",
    slug: "kling-ai",
    description: "Kuaishou's budget-friendly AI video generator. Strong character consistency and smooth motion. Independent reviewers consistently rank it as the best value option in the AI video space.",
    url: "https://klingai.com",
    affiliate: "",
    category: "video",
    pricing: "freemium",
    badge: "trending",
    tags: ["video generation", "budget-friendly", "character consistency"],
    scenarios: ["creators", "social media"],
    alternatives: ["runway", "pika", "sora"]
  },
  {
    id: 17,
    name: "GitHub Copilot",
    slug: "github-copilot",
    description: "1.3M+ paid users. Deeply integrated into VS Code and JetBrains. Copilot X adds chat, code review, CLI agent mode, and workspace-aware completions. The enterprise-safe default for team adoption.",
    url: "https://github.com/features/copilot",
    affiliate: "",
    category: "coding",
    pricing: "paid",
    badge: "",
    tags: ["code completion", "IDE", "code review", "enterprise", "agent"],
    scenarios: ["developers", "business"],
    alternatives: ["cursor", "windsurf", "claude-code", "devin"]
  },
  {
    id: 18,
    name: "Cursor",
    slug: "cursor",
    description: "The AI code editor valued at $9B. Chat with your entire codebase, apply multi-file edits inline, and enjoy VS Code compatibility with AI superpowers. The default choice for individual developers in 2026.",
    url: "https://cursor.com",
    affiliate: "",
    category: "coding",
    pricing: "freemium",
    badge: "hot",
    tags: ["code editor", "AI programming", "codebase chat", "multi-file"],
    scenarios: ["developers"],
    alternatives: ["github-copilot", "windsurf", "claude-code"]
  },
  {
    id: 19,
    name: "Windsurf",
    slug: "windsurf",
    description: "Codeium's AI IDE with Cascade agent — writes multi-file changes autonomously, executes terminal commands, and understands full project context. The most agentic IDE experience available.",
    url: "https://codeium.com/windsurf",
    affiliate: "",
    category: "coding",
    pricing: "freemium",
    badge: "trending",
    tags: ["AI IDE", "agentic coding", "multi-file", "terminal"],
    scenarios: ["developers"],
    alternatives: ["cursor", "github-copilot", "claude-code"]
  },
  {
    id: 20,
    name: "Claude Code",
    slug: "claude-code",
    description: "Anthropic's terminal-native coding agent. Full project context, git-aware, shell-native. Updated frequently — major releases tracked monthly. The secret weapon for senior developers doing complex refactors.",
    url: "https://docs.anthropic.com/en/docs/claude-code",
    affiliate: "",
    category: "coding",
    pricing: "paid",
    badge: "trending",
    tags: ["terminal", "agent", "coding", "git", "shell"],
    scenarios: ["developers"],
    alternatives: ["cursor", "github-copilot", "windsurf", "devin"]
  },
  {
    id: 21,
    name: "Devin",
    slug: "devin",
    description: "Cognition's AI software engineer — now Devin 2.0 with improved planning, debugging, and deployment capabilities. Handles entire features, bug fixes, and PRs autonomously. Works while you sleep.",
    url: "https://cognition.ai",
    affiliate: "",
    category: "coding",
    pricing: "paid",
    badge: "trending",
    tags: ["AI engineer", "autonomous coding", "agent", "deployment"],
    scenarios: ["developers", "business"],
    alternatives: ["claude-code", "cursor", "windsurf"]
  },
  {
    id: 22,
    name: "Bolt.new",
    slug: "bolt-new",
    description: "Prompt-to-fullstack-app in your browser. Describe your app idea and Bolt generates a running web application with frontend, backend, and database. One-click deploy. Fastest path from idea to live product.",
    url: "https://bolt.new",
    affiliate: "",
    category: "coding",
    pricing: "freemium",
    badge: "hot",
    tags: ["app builder", "fullstack", "no-code", "deploy"],
    scenarios: ["developers", "business", "creators"],
    alternatives: ["lovable", "replit-agent", "v0"]
  },
  {
    id: 23,
    name: "ElevenLabs",
    slug: "elevenlabs",
    description: "Industry-leading AI voice synthesis and cloning in 32 languages. Voiceovers, audiobook narration, voice cloning from 60-second samples, and AI music generation. The gold standard for realistic AI speech.",
    url: "https://elevenlabs.io",
    affiliate: "",
    category: "audio",
    pricing: "freemium",
    badge: "hot",
    tags: ["text-to-speech", "voice cloning", "audiobooks", "multilingual"],
    scenarios: ["creators", "marketing", "business", "education"],
    alternatives: ["murf-ai", "descript", "suno"]
  },
  {
    id: 24,
    name: "Suno",
    slug: "suno",
    description: "Create full, radio-quality songs from text prompts. V4 delivers improved vocals, richer instrumentation, and longer compositions. Describe a genre and theme, get a complete song in seconds.",
    url: "https://suno.ai",
    affiliate: "",
    category: "audio",
    pricing: "freemium",
    badge: "hot",
    tags: ["music generation", "songs", "lyrics", "creative"],
    scenarios: ["creators", "social media"],
    alternatives: ["udio", "elevenlabs"]
  },
  {
    id: 25,
    name: "Udio",
    slug: "udio",
    description: "AI music generator by former Google DeepMind researchers. Known for high-quality instrumentals and vocal realism. A strong Suno alternative with a different creative flavor profile.",
    url: "https://udio.com",
    affiliate: "",
    category: "audio",
    pricing: "freemium",
    badge: "",
    tags: ["music generation", "instrumentals", "vocals", "creative"],
    scenarios: ["creators"],
    alternatives: ["suno", "elevenlabs"]
  },
  {
    id: 26,
    name: "Perplexity",
    slug: "perplexity",
    description: "AI-powered search engine with citations and deep research mode. Combines LLM intelligence with live web access. The go-to research companion for fact-checked, source-verified answers in 2026.",
    url: "https://perplexity.ai",
    affiliate: "",
    category: "research",
    pricing: "freemium",
    badge: "hot",
    tags: ["search", "research", "citations", "deep research"],
    scenarios: ["students", "research", "business"],
    alternatives: ["chatgpt", "notebooklm", "gemini"]
  },
  {
    id: 27,
    name: "Grammarly",
    slug: "grammarly",
    description: "The ubiquitous AI writing assistant. Beyond grammar — tone adjustments, generative rewriting, plagiarism detection, and enterprise style guides. Works across every app and browser seamlessly.",
    url: "https://grammarly.com",
    affiliate: "",
    category: "writing",
    pricing: "freemium",
    badge: "",
    tags: ["grammar", "writing", "tone", "proofreading", "enterprise"],
    scenarios: ["students", "business", "marketing"],
    alternatives: ["jasper", "chatgpt", "claude"]
  },
  {
    id: 28,
    name: "Jasper",
    slug: "jasper",
    description: "Enterprise AI marketing platform for on-brand content at scale. Blog posts, ad copy, emails, and social content with built-in brand voice. Marketing teams at mid-to-large companies rely on it daily.",
    url: "https://jasper.ai",
    affiliate: "",
    category: "writing",
    pricing: "paid",
    badge: "",
    tags: ["content marketing", "copywriting", "brand voice", "enterprise"],
    scenarios: ["marketing", "business"],
    alternatives: ["copy-ai", "chatgpt", "grammarly"]
  },
  {
    id: 29,
    name: "Canva AI",
    slug: "canva-ai",
    description: "Canva's Magic Studio brings AI design to 200M+ users. AI design generation, background remover, Magic Write, and brand kit automation. The most accessible AI design tool for non-designers.",
    url: "https://canva.com",
    affiliate: "",
    category: "design",
    pricing: "freemium",
    badge: "",
    tags: ["graphic design", "branding", "templates", "magic studio"],
    scenarios: ["designers", "marketing", "business", "students"],
    alternatives: ["figma-ai", "adobe-firefly", "gamma"]
  },
  {
    id: 30,
    name: "Figma AI",
    slug: "figma-ai",
    description: "AI features in the industry-standard UI/UX design tool. Auto-layout, design-to-code, AI asset generation, and smart layer renaming. Essential for product design teams building interfaces.",
    url: "https://figma.com",
    affiliate: "",
    category: "design",
    pricing: "freemium",
    badge: "",
    tags: ["UI design", "prototyping", "design-to-code", "collaboration"],
    scenarios: ["designers", "developers"],
    alternatives: ["canva-ai", "adobe-firefly"]
  },
  {
    id: 31,
    name: "Notion AI",
    slug: "notion-ai",
    description: "AI deeply embedded in the world's most flexible workspace. Summarize, generate, translate, Q&A your knowledge base, and automate workflows. Used by millions of teams and individuals daily.",
    url: "https://notion.so/product/ai",
    affiliate: "",
    category: "productivity",
    pricing: "paid",
    badge: "",
    tags: ["notes", "knowledge management", "automation", "workspace"],
    scenarios: ["business", "students", "developers"],
    alternatives: ["gamma", "chatgpt", "claude"]
  },
  {
    id: 32,
    name: "Gamma",
    slug: "gamma",
    description: "Create beautiful presentations, documents, and web pages in seconds. Paste an outline and Gamma generates polished, interactive decks with AI images. Export to PPTX or publish live. Perfect for pitch decks.",
    url: "https://gamma.app",
    affiliate: "",
    category: "productivity",
    pricing: "freemium",
    badge: "trending",
    tags: ["presentations", "documents", "publishing", "design"],
    scenarios: ["business", "students", "marketing"],
    alternatives: ["canva-ai", "notion-ai"]
  },
  {
    id: 33,
    name: "Copy.ai",
    slug: "copy-ai",
    description: "The first GTM (go-to-market) AI platform. Automates sales prospecting, marketing campaigns, lead enrichment, and workflow orchestration. AI agents work in concert for end-to-end GTM motions.",
    url: "https://copy.ai",
    affiliate: "",
    category: "marketing",
    pricing: "freemium",
    badge: "",
    tags: ["GTM", "sales", "workflows", "agents", "marketing automation"],
    scenarios: ["marketing", "business"],
    alternatives: ["jasper", "chatgpt", "claude"]
  },
  {
    id: 34,
    name: "Synthesia",
    slug: "synthesia",
    description: "Create professional videos with photorealistic AI avatars — no cameras or studios needed. 140+ languages. 50,000+ companies use it for training, marketing, and personalized sales outreach.",
    url: "https://synthesia.io",
    affiliate: "",
    category: "video",
    pricing: "paid",
    badge: "",
    tags: ["AI avatars", "video creation", "enterprise", "multilingual"],
    scenarios: ["business", "marketing", "education"],
    alternatives: ["heygen", "runway", "descript"]
  },
  {
    id: 35,
    name: "Manus",
    slug: "manus",
    description: "The breakout autonomous AI agent of 2026. Manus browses the web, operates software, analyzes data, and executes multi-step tasks independently. Represents the shift from chat to autonomous action.",
    url: "https://manus.im",
    affiliate: "",
    category: "agents",
    pricing: "freemium",
    badge: "hot",
    tags: ["AI agent", "autonomous", "browser", "task execution"],
    scenarios: ["developers", "business", "research"],
    alternatives: ["devin", "agentgpt", "crewai"]
  },
  {
    id: 36,
    name: "CrewAI",
    slug: "crewai",
    description: "Leading multi-agent orchestration framework. Define roles, assign tasks, and let AI agents collaborate autonomously. The most popular production framework for building agent teams in 2026.",
    url: "https://crewai.com",
    affiliate: "",
    category: "agents",
    pricing: "freemium",
    badge: "trending",
    tags: ["multi-agent", "orchestration", "framework", "autonomous"],
    scenarios: ["developers", "business"],
    alternatives: ["autogpt", "langchain", "autogen"]
  },
  {
    id: 37,
    name: "AutoGPT",
    slug: "autogpt",
    description: "The original autonomous AI agent — now revitalized in 2026 with improved reliability, browser control, and task planning. Define a goal and AutoGPT breaks it down, executes steps, and iterates until completion.",
    url: "https://autogpt.net",
    affiliate: "",
    category: "agents",
    pricing: "free",
    badge: "trending",
    tags: ["AI agent", "autonomous", "goal-driven", "open source"],
    scenarios: ["developers", "research"],
    alternatives: ["crewai", "manus", "agentgpt"]
  },
  {
    id: 38,
    name: "Gemma",
    slug: "gemma",
    description: "Google's open-source Gemma 4 — lightweight, powerful, and mobile-ready. Runs on-device with impressive performance. Part of Google's commitment to open AI alongside the proprietary Gemini line.",
    url: "https://ai.google.dev/gemma",
    affiliate: "",
    category: "chat",
    pricing: "free",
    badge: "trending",
    tags: ["open source", "on-device", "lightweight", "mobile"],
    scenarios: ["developers", "research"],
    alternatives: ["llama-4", "deepseek", "qwen", "mistral"]
  }
];

const CATEGORIES = [
  { id: "all", name: "All Tools", icon: "✨" },
  { id: "chat", name: "Chat & Assistants", icon: "💬" },
  { id: "writing", name: "Writing", icon: "✍️" },
  { id: "image", name: "Image Generation", icon: "🎨" },
  { id: "video", name: "Video", icon: "🎬" },
  { id: "coding", name: "Coding", icon: "💻" },
  { id: "agents", name: "AI Agents", icon: "🤖" },
  { id: "audio", name: "Audio & Music", icon: "🎵" },
  { id: "design", name: "Design", icon: "🎯" },
  { id: "marketing", name: "Marketing", icon: "📢" },
  { id: "productivity", name: "Productivity", icon: "⚡" },
  { id: "research", name: "Research", icon: "🔬" }
];

const PRICING_OPTIONS = [
  { id: "all", name: "All" },
  { id: "free", name: "Free" },
  { id: "freemium", name: "Freemium" },
  { id: "paid", name: "Paid" }
];

const SCENARIOS = [
  { id: "developers", name: "For Developers", icon: "💻", description: "AI tools for coding faster, debugging smarter, and shipping better software." },
  { id: "marketing", name: "For Marketing", icon: "📢", description: "Content creation, copywriting, social media, and campaign automation." },
  { id: "designers", name: "For Designers", icon: "🎨", description: "Image generation, UI design, branding, and creative asset production." },
  { id: "creators", name: "For Creators", icon: "🎬", description: "Video, audio, music, and content creation for YouTubers, podcasters, and artists." },
  { id: "business", name: "For Business", icon: "💼", description: "Productivity, automation, presentations, and enterprise AI solutions." },
  { id: "students", name: "For Students", icon: "📚", description: "Research, writing, studying, and learning tools to ace academic work." }
];

const SORT_OPTIONS = [
  { id: "default", name: "Featured" },
  { id: "name-asc", name: "Name A-Z" },
  { id: "name-desc", name: "Name Z-A" },
  { id: "newest", name: "Newest First" },
  {
    id: 39,
    name: "Veo 3",
    slug: "veo-3",
    description: "Google DeepMind's latest video generation model. Competes directly with Sora and Runway with high-quality, coherent video output.",
    url: "https://deepmind.google/technologies/veo/",
    affiliate: "",
    category: "video",
    pricing: "paid",
    badge: "trending",
    tags: ["video generation", "google", "professional"],
    scenarios: ["creators", "filmmaking", "marketing"],
    alternatives: ["sora", "runway", "kling-ai"]
  },
  {
    id: 40,
    name: "Lovable",
    slug: "lovable",
    description: "AI-powered full-stack app builder. Describe your app idea and Lovable generates a complete, deployable web application with beautiful design.",
    url: "https://lovable.dev",
    affiliate: "",
    category: "coding",
    pricing: "freemium",
    badge: "trending",
    tags: ["app builder", "fullstack", "no-code", "deploy"],
    scenarios: ["developers", "business", "creators"],
    alternatives: ["bolt-new", "replit-agent", "v0"]
  },
  {
    id: 41,
    name: "v0 by Vercel",
    slug: "v0",
    description: "Vercel's AI UI generator. Describe a UI component and v0 generates production-ready React/Tailwind code. Widely used by frontend developers.",
    url: "https://v0.dev",
    affiliate: "",
    category: "coding",
    pricing: "freemium",
    badge: "hot",
    tags: ["UI generation", "React", "frontend", "design-to-code"],
    scenarios: ["developers", "designers"],
    alternatives: ["bolt-new", "lovable", "cursor"]
  },
  {
    id: 42,
    name: "Replit Agent",
    slug: "replit-agent",
    description: "Replit's AI agent that builds and deploys full applications from natural language. Online IDE with autonomous coding capabilities.",
    url: "https://replit.com",
    affiliate: "",
    category: "coding",
    pricing: "freemium",
    badge: "",
    tags: ["online IDE", "AI agent", "deploy", "fullstack"],
    scenarios: ["developers", "students"],
    alternatives: ["bolt-new", "lovable", "cursor"]
  },
  {
    id: 43,
    name: "HeyGen",
    slug: "heygen",
    description: "AI video platform for creating talking avatars and translating videos into 40+ languages with lip-sync. Popular for corporate training and personalized video outreach.",
    url: "https://heygen.com",
    affiliate: "",
    category: "video",
    pricing: "paid",
    badge: "",
    tags: ["AI avatars", "video translation", "lip sync", "enterprise"],
    scenarios: ["business", "marketing", "creators"],
    alternatives: ["synthesia", "descript"]
  },
  {
    id: 44,
    name: "Descript",
    slug: "descript",
    description: "AI-powered video and audio editor. Edit media by editing text — delete words from the transcript and they disappear from the video. Voice cloning and podcast tools built in.",
    url: "https://descript.com",
    affiliate: "",
    category: "audio",
    pricing: "freemium",
    badge: "",
    tags: ["video editing", "transcription", "voice cloning", "podcast"],
    scenarios: ["creators", "marketing", "business"],
    alternatives: ["elevenlabs", "synthesia", "heygen"]
  },
  {
    id: 45,
    name: "NotebookLM",
    slug: "notebooklm",
    description: "Google's AI research assistant. Upload documents and it generates summaries, FAQs, study guides, and even AI-hosted podcast discussions about your content. Free and powerful.",
    url: "https://notebooklm.google.com",
    affiliate: "",
    category: "research",
    pricing: "free",
    badge: "hot",
    tags: ["research", "notes", "podcast", "google", "summarization"],
    scenarios: ["students", "research", "business"],
    alternatives: ["perplexity", "chatgpt", "claude"]
  },
  {
    id: 46,
    name: "Recraft",
    slug: "recraft",
    description: "AI design tool focused on brand-consistent image generation. Create logos, illustrations, and marketing assets that match your brand style. Supports raster and vector output.",
    url: "https://recraft.ai",
    affiliate: "",
    category: "image",
    pricing: "freemium",
    badge: "trending",
    tags: ["image generation", "vector", "brand", "design system"],
    scenarios: ["designers", "marketing", "business"],
    alternatives: ["midjourney", "adobe-firefly", "canva-ai", "ideogram"]
  },
  {
    id: 47,
    name: "Hailuo AI",
    slug: "hailuo-ai",
    description: "Fast, high-quality AI video generator from MiniMax. Known for quick generation times and competitive output quality in the crowded AI video space.",
    url: "https://hailuoai.video",
    affiliate: "",
    category: "video",
    pricing: "freemium",
    badge: "",
    tags: ["video generation", "text-to-video", "fast"],
    scenarios: ["creators", "social media", "marketing"],
    alternatives: ["runway", "pika", "kling-ai", "sora"]
  },
  {
    id: 48,
    name: "Murf AI",
    slug: "murf-ai",
    description: "AI voiceover studio with 120+ realistic voices in 20+ languages. Sync voiceovers with video, adjust pitch and speed. Popular among content creators and e-learning professionals.",
    url: "https://murf.ai",
    affiliate: "",
    category: "audio",
    pricing: "freemium",
    badge: "",
    tags: ["text-to-speech", "voiceover", "video voiceover", "multilingual"],
    scenarios: ["creators", "marketing", "education"],
    alternatives: ["elevenlabs", "descript"]
  },
  {
    id: 49,
    name: "Stable Diffusion 3.5",
    slug: "stable-diffusion",
    description: "Stability AI's latest open-weight image model. Run locally on consumer hardware with full control. Massive community of fine-tuned models and LoRAs for any style.",
    url: "https://stability.ai",
    affiliate: "",
    category: "image",
    pricing: "free",
    badge: "",
    tags: ["image generation", "open source", "local", "customizable"],
    scenarios: ["designers", "developers", "creators"],
    alternatives: ["midjourney", "dall-e-3", "adobe-firefly"]
  },
  {
    id: 50,
    name: "Durable",
    slug: "durable",
    description: "AI website builder for small businesses. Generate a complete business website with copy, images, and forms in 30 seconds. Includes CRM and invoicing tools.",
    url: "https://durable.co",
    affiliate: "",
    category: "productivity",
    pricing: "paid",
    badge: "",
    tags: ["website builder", "small business", "AI website", "marketing"],
    scenarios: ["business", "marketing"],
    alternatives: ["gamma", "bolt-new"]
  }

];
